### ISSUE TITLE
Upload Image minify/base64

### ISSUE THREAD

**Issue by Backins** [dycor/twitbook#11]
Afin de gagner en PWA, il faut resize les images et les passer en base 64

**Comment by Backins** [comment]
la base 64 servira en attendant de ravoir l'image complète. Schema imaginé : 

- minifier l'image sans la stocker
- obtenir le base64
- enregistrer le base64
- upload l'image non minifié

A l'affichage : 
- affichée le base 64
- lorsque l'image est chargé, affiché l'image non minifié

Est-ce bon comme schema ? Je vois à peu près comment faire l'ensemble sauf la fin

**Comment by dycor** [comment]
t'entends par la que la base64 est minifié ?

**Comment by Backins** [comment]
Non, tu minifie l'image et ensuite tu fais le base64

**Comment by Backins** [comment]
C'est en place sur une des PR
